language: rust

sudo: required

branches:
  only:
    - main

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
  - rust: nightly

addons:
  apt:
    packages:

script:
  - sudo apt-get install libhdf5-dev
  - cargo build --all-features
  - cargo test --all-features
