language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
  - rust: nightly

addons:
  apt:
    packages:

script:
  - cargo build --all-features
  - cargo test
